server:
  port: 10004
spring:
  application:
    name: userAdmin-management-platform
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 1024MB
  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:classpath:sharding-config.yaml
  data:
    redis:
      lettuce:
        pool:
          max-idle: 5
          max-active: 10
          min-idle: 2
          max-wait: 1000ms
      host: fantasyz.top
      port: 16379
sa-token:
  token-name: satoken
  # token 有效期（单位：秒） 默认30天，-1 代表永久有效
  timeout: 604800
  # token 最低活跃频率（单位：秒），如果 token 超过此时间没有访问系统就会被冻结，默认-1 代表不限制，永不冻结
  active-timeout: -1
  # 是否允许同一账号多地同时登录 （为 true 时允许一起登录, 为 false 时新登录挤掉旧登录）
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个 token （为 true 时所有登录共用一个 token, 为 false 时每次登录新建一个 token）
  is-share: false
  # token 风格（默认可取值：uuid、simple-uuid、random-32、random-64、random-128、tik）
  token-style: uuid
  # 是否输出操作日志
  is-log: true
rustfs:
  endpoint: http://fantasyz.top:31001
  accessKey: rustfsadmin
  secretKey: rustfsadmin123
  ##us-east-1\b2c-coupon-platform
  region: b2c-coupon-platform
  bucket: user-admin-image-bucket