server:
  port: 10002
spring:
  application:
    name: coupon-management-platform
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 1024MB
  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:classpath:sharding-config.yaml
  data:
    redis:
      lettuce:
        pool:
          max-idle: 10
          max-active: 20
          min-idle: 5
          max-wait: 1000ms
      host: fantasyz.top
      port: 16379
rocketmq:
  name-server: common-rocketmq-dev.magestack.cn:9876
  producer:
    group: b2c-coupon-system_coupon-management-producer-group
    send-message-timeout: 2000
    retry-times-when-send-failed: 1
    retry-times-when-send-async-failed: 1